{% set name = "types-networkx" %}
{% set version = "3.5.0.20250816" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types_networkx-{{ version }}.tar.gz
  sha256: 7947de7e58fc75cb6d97bc2e68f62b35530fe046cda1409cec3036008405c324

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20

test:
  commands:
    - pip check
    - test -f $SP_DIR/networkx-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\networkx-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for networkx
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - '0xbe7a'
