{% set name = "types-networkx" %}
{% set version = "3.4.2.20241115" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-networkx-{{ version }}.tar.gz
  sha256: d669b650cf6c6c9ec879a825449eb04a5c10742f3109177e1683f57ee49e0f59

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy <2

test:
  commands:
    - pip check
    - test -f $SP_DIR/networkx-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\networkx-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for networkx
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - '0xbe7a'
