{% set name = "types-networkx" %}
{% set version = "3.4.2.20250426" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types_networkx-{{ version }}.tar.gz
  sha256: f1b73e144fb7072a5c1625fd5edc72bfaf93d4844eab4706b786faa10b2dc1a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20

test:
  commands:
    - pip check
    - test -f $SP_DIR/networkx-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\networkx-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for networkx
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - '0xbe7a'
