{% set name = "types-networkx" %}
{% set version = "3.2.1.20240518" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-networkx-{{ version }}.tar.gz
  sha256: fc8149ccb7ed057f2030a80e2f9a257fd101a34c4818a6921a123acb6ab929fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy

test:
  commands:
    - pip check
    - test -f $SP_DIR/networkx-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\networkx-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for networkx
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - '0xbe7a'
