schema_version: 1

context:
  name: types-networkx
  version: "3.6.1.20260903"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/types_networkx-${{ version }}.tar.gz
  sha256: 31446a57554e593bffdf9078fef045df3084e6b8b31902e75cd512622142504d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.20

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

  - package_contents:
      site_packages:
        - networkx-stubs/__init__.pyi

about:
  summary: Typing stubs for networkx
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed
  repository: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - fhoehle
    - '0xbe7a'
